name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Debug directory structure to ensure correct files are present
      - name: Debug Directory
        run: |
          echo "Current Directory:"
          pwd
          echo "Contents of Current Directory:"
          ls -la
          echo "Contents of my-frontend Directory:"
          ls -la my-frontend

      # Set up Node.js environment with caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Install dependencies inside `my-frontend`
      - name: Install dependencies
        working-directory: my-frontend
        run: npm ci  # Use npm ci to install the exact versions specified in package-lock.json

      # Build the project
      - name: Build the project
        working-directory: my-frontend
        run: npm run build

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FULL_STACK_APP_127BE }}
          projectId: full-stack-app-127be