name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          path: .

      # Debug the root directory and subdirectories
      - name: Debug Directory
        run: |
          echo "Root Directory (pwd):"
          pwd
          echo "Root Directory Contents:"
          ls -la
          echo "Contents of my-frontend:"
          ls -la ./my-frontend

      # Set up Node.js environment with caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./my-frontend/package-lock.json

      # Explicitly set working directory for dependency installation
      - name: Install Dependencies
        run: npm ci
        working-directory: ./my-frontend

      # Build the project in the correct directory
      - name: Build Project
        run: npm run build
        working-directory: ./my-frontend

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FULL_STACK_APP_127BE }}
          projectId: full-stack-app-127be