name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Debug the current directory to verify structure
      - name: Debug Directory
        run: |
          echo "Current Directory:"
          pwd
          echo "Contents of Current Directory:"
          ls -la

      # Set up Node.js with caching
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Debug the contents of `my-frontend` folder
      - name: Debug my-frontend Folder
        run: |
          echo "Contents of my-frontend:"
          ls -la my-frontend

      # Navigate to `my-frontend` and install dependencies
      - name: Install Dependencies
        working-directory: my-frontend
        run: npm ci

      # Build the frontend
      - name: Build Frontend
        working-directory: my-frontend
        run: npm run build

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FULL_STACK_APP_127BE }}
          projectId: full-stack-app-127be